In [2]:
import numpy as np
arr = np.arange(10)
print("2)", arr)

logical_arr = np.full((3, 3), True, dtype=bool)
print("3)", logical_arr)

odd_nums = arr[arr % 2 != 0]
print("4)", odd_nums)

arr[arr % 2 != 0] = -1
print("5)", arr)

arr = np.arange(10)
out = np.where(arr % 2 != 0, -1, arr)
print("6) out\n", out)
print("6) arr\n", arr)

arr_2d = np.arange(10).reshape(2, -1)
print("7)", arr_2d)

a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
result = np.vstack([a, b])
print("8)", result)

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
horizontal_stack = np.hstack([a, b])
print("9)", horizontal_stack)

a = np.array([2, 6, 1, 9, 10, 3, 27])
desired_result = np.where((a >= 5) & (a <= 10))
print("14)", a[desired_result])

arr = np.arange(9).reshape(3,3)
arr[:, [1, 2]] = arr[:, [2, 1]]
print("16)", arr)

arr = np.arange(9).reshape(3,3)
arr[[1, 2], :] = arr[[2, 1], :]
print("17)", arr)

arr = np.arange(9).reshape(3,3)
arr[[0, -1], :] = arr[[-1, 0], :]
print("18)", arr)

arr = np.arange(9).reshape(3,3)
arr[:, [0, -1]] = arr[:, [-1, 0]]
print("19)", arr)

random_decimal_array = np.random.uniform(5, 10, size=(5, 3))
print("20)", random_decimal_array)


2) [0 1 2 3 4 5 6 7 8 9]
3) [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
4) [1 3 5 7 9]
5) [ 0 -1  2 -1  4 -1  6 -1  8 -1]
6) out
 [ 0 -1  2 -1  4 -1  6 -1  8 -1]
6) arr
 [0 1 2 3 4 5 6 7 8 9]
7) [[0 1 2 3 4]
 [5 6 7 8 9]]
8) [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
9) [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
14) [ 6  9 10]
16) [[0 2 1]
 [3 5 4]
 [6 8 7]]
17) [[0 1 2]
 [6 7 8]
 [3 4 5]]
18) [[6 7 8]
 [3 4 5]
 [0 1 2]]
19) [[2 1 0]
 [5 4 3]
 [8 7 6]]
20) [[9.97898224 7.90061923 8.24020678]
 [6.31348259 9.81722952 5.65443188]
 [5.28822974 5.46813794 7.67576522]
 [6.42747467 5.49884378 7.34344096]
 [9.1810529  8.0096024  9.15548989]]
