# Классная работа 7

## Раздел 1

Пункты 1-2

In [18]:
import pandas as pd
import numpy as np
import sklearn.model_selection as skms
import sklearn.linear_model as sklm
import sklearn.svm as sksv
import sklearn.discriminant_analysis as skda
import pingouin as pg

filename = 'data/pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = pd.read_csv(filename, names = names)
data.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

Пункты 3-4

In [19]:
array = data.values
x = array[:, :-1]
y = array[:, -1]

X - признаки, предположительно влияющие на статус диабета

Y - статус диабета

Пункты 5-8

In [20]:
kfold = skms.KFold(n_splits = 10, random_state = 7, shuffle=True)
model1 = sklm.LogisticRegression(solver='liblinear')
result_cv1 = skms.cross_val_score(model1, x, y, cv=kfold)
print(result_cv1.mean(), result_cv1.std())

0.7708646616541353 0.05090500786917546


Пункты 9-10

In [21]:
model1.fit(x, y)
print(model1.intercept_)
print(model1.coef_)

[-5.89086481]
[[ 1.17048205e-01  2.83845957e-02 -1.68888600e-02  7.55799415e-04
  -6.42571814e-04  5.97485192e-02  6.77694300e-01  7.23791433e-03]]


УР для preg: y = 1.17061865e-01 * x + (-5.89249766)

plas: y = 2.83893855e-02 * x + (-5.89249766)

и т.д. с заменой коэффициента на соответствующий признаку

Пункты 11-13

In [22]:
x_new = np.array([[0,136,42,34,136,43,2,32],[0,137,40,35,168,43.1,2.288,33]])
print(model1.predict(x_new))
print(model1.predict_proba(x_new))

[1. 1.]
[[0.20511875 0.79488125]
 [0.16723545 0.83276455]]


## Раздел 2

Пункты 14-16

In [23]:
model2 = sksv.SVC(kernel='linear')
result_cv2 = skms.cross_val_score(model2, x, y, cv=kfold)
print(result_cv2.mean(), result_cv2.std())

0.7708133971291866 0.03832392703883875


Пункты 17-19

In [24]:
model2.fit(x, y)
print(model2.intercept_)
print(model2.coef_)
print(model2.predict(x_new))

[-6.74057169]
[[ 9.14678567e-02  3.00464508e-02 -1.09048360e-02 -4.81644395e-03
  -4.21237445e-04  7.33942693e-02  7.15044864e-01  7.26113767e-03]]
[1. 1.]


Пункт 20

In [25]:
model22 = sksv.SVC(kernel='rbf')
model22.fit(x, y)
print(model22.predict(x_new))

[0. 0.]


## Раздел 3

Пункт 21

In [26]:
pg.multivariate_normality(x, alpha=.05)

HZResults(hz=4.18048602737756, pval=0.0, normal=False)

H0: дискиминативные переменные распределены нормально

&alpha; = 0.05

pval < &alpha; -> отвергаем H0, переменные не распределены нормально

Пункт 22

In [27]:
pg.normality(data)

W          pval  normal
preg   0.904283  1.610010e-21   False
plas   0.970105  1.987465e-11   False
pres   0.818923  1.584494e-28   False
skin   0.904628  1.751800e-21   False
test   0.722021  7.915340e-34   False
mass   0.949989  1.840759e-15   False
pedi   0.836519  2.477799e-27   False
age    0.874766  2.401830e-24   False
class  0.602510  1.292262e-38   False

 W - численное значение, которое тест Шапиро-Уилка использует для оценки отклонения данных от нормального распределения. Чем ближе значение W к 1, тем больше шансов, что данные были взяты из нормального распределения.

 Однако шансы себя не оправдали, pval каждого из признаков намного меньше заданного нами &alpha; = 0.05, следовательно, все признаки не имеют нормального распределения.

 В данных условиях добиться многомерной нормальности распределения дискриминантных переменных будет трудно.

Пункт 23

In [28]:
pg.box_m(data, dvs=['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age'], group='class')

Chi2    df          pval  equal_cov
box  226.706491  36.0  1.642145e-29      False

H0: Ковариационные матрицы приблизительно равны для каждого класса

&alpha; = 0.05

pval < &alpha; -> отвергаем H0, матрицы не равны.


Пункт 24

In [29]:
pg.pairwise_corr(data, columns=['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age'], method='pearson')

X     Y   method alternative    n         r           CI95%  \
0   preg  plas  pearson   two-sided  768  0.129459     [0.06, 0.2]   
1   preg  pres  pearson   two-sided  768  0.141282    [0.07, 0.21]   
2   preg  skin  pearson   two-sided  768 -0.081672  [-0.15, -0.01]   
3   preg  test  pearson   two-sided  768 -0.073535   [-0.14, -0.0]   
4   preg  mass  pearson   two-sided  768  0.017683   [-0.05, 0.09]   
5   preg  pedi  pearson   two-sided  768 -0.033523    [-0.1, 0.04]   
6   preg   age  pearson   two-sided  768  0.544341    [0.49, 0.59]   
7   plas  pres  pearson   two-sided  768  0.152590    [0.08, 0.22]   
8   plas  skin  pearson   two-sided  768  0.057328   [-0.01, 0.13]   
9   plas  test  pearson   two-sided  768  0.331357    [0.27, 0.39]   
10  plas  mass  pearson   two-sided  768  0.221071    [0.15, 0.29]   
11  plas  pedi  pearson   two-sided  768  0.137337    [0.07, 0.21]   
12  plas   age  pearson   two-sided  768  0.263514     [0.2, 0.33]   
13  pres  skin  pearson   two-sided  768  0.207371    [0.14, 0.27]   
14  pres  test  pearson   two-sided  768  0.088933    [0.02, 0.16]   
15  pres  mass  pearson   two-sided  768  0.281805    [0.22, 0.35]   
16  pres  pedi  pearson   two-sided  768  0.041265   [-0.03, 0.11]   
17  pres   age  pearson   two-sided  768  0.239528    [0.17, 0.31]   
18  skin  test  pearson   two-sided  768  0.436783    [0.38, 0.49]   
19  skin  mass  pearson   two-sided  768  0.392573    [0.33, 0.45]   
20  skin  pedi  pearson   two-sided  768  0.183928    [0.11, 0.25]   
21  skin   age  pearson   two-sided  768 -0.113970  [-0.18, -0.04]   
22  test  mass  pearson   two-sided  768  0.197859    [0.13, 0.26]   
23  test  pedi  pearson   two-sided  768  0.185071    [0.12, 0.25]   
24  test   age  pearson   two-sided  768 -0.042163   [-0.11, 0.03]   
25  mass  pedi  pearson   two-sided  768  0.140647    [0.07, 0.21]   
26  mass   age  pearson   two-sided  768  0.036242   [-0.03, 0.11]   
27  pedi   age  pearson   two-sided  768  0.033561    [-0.04, 0.1]   

           p-unc       BF10     power  
0   3.219491e-04     28.791  0.949814  
1   8.541846e-05    100.059  0.975945  
2   2.360795e-02      0.583  0.619944  
3   4.162094e-02      0.359  0.531407  
4   6.246376e-01      0.051  0.077839  
5   3.535346e-01      0.069  0.152973  
6   1.862813e-60   9.03e+56  1.000000  
7   2.169507e-05    366.214  0.989169  
8   1.124141e-01      0.159  0.355230  
9   3.882624e-21  8.929e+17  1.000000  
10  5.891413e-10  9.293e+06  0.999990  
11  1.345878e-04     65.209  0.968913  
12  1.150112e-13  3.936e+10  1.000000  
13  6.606687e-09   8.86e+05  0.999944  
14  1.368350e-02      0.939  0.694191  
15  1.737888e-15  2.415e+12  1.000000  
16  2.533744e-01      0.087  0.207803  
17  1.752051e-11  2.869e+08  0.999999  
18  4.043577e-37  5.944e+33  1.000000  
19  1.054876e-29  2.645e+26  1.000000  
20  2.856179e-07  2.316e+04  0.999286  
21  1.558278e-03      6.673  0.886463  
22  3.219695e-08  1.908e+05  0.999834  
23  2.402264e-07  2.737e+04  0.999363  
24  2.431822e-01      0.089  0.214909  
25  9.197970e-05     93.315  0.974912  
26  3.158330e-01      0.075  0.170892  
27  3.529797e-01       0.07  0.153217

pval > 0.05 в следующих парах: 4, 5, 8, 16, 24, 26, 27. Следовательно, в этих парах можно наблюдать линейную независимость (H0 подтверждается), в остальных случаях будет присутствовать линейная зависимость (H0 отвергается)


Пункт 25

Дискриминантный анализ не представляется возможным, из-за отсутствия нормального распределения каждого класса, а также наличия линейно зависимых пар.

Пункты 26-28

In [30]:
model3 = skda.LinearDiscriminantAnalysis()
result_cv3 = skms.cross_val_score(model3, x, y, cv=kfold)
print(result_cv3.mean(), result_cv3.std())

0.7669685577580315 0.04796563054016723


Пункты 29-31

In [31]:
model3.fit(x, y)
print(model3.predict(x_new))
print(model3.predict_proba(x_new))

[1. 1.]
[[0.13996295 0.86003705]
 [0.10537183 0.89462817]]


Пункт 32

In [32]:
print(model3.transform(x)[:5])

[[ 1.38024702]
 [-1.56452399]
 [ 1.76618515]
 [-1.69058752]
 [ 2.20726804]]


Пункт 33

In [33]:
print(model3.fit_transform(x, y)[:5])

[[ 1.38024702]
 [-1.56452399]
 [ 1.76618515]
 [-1.69058752]
 [ 2.20726804]]
