In [17]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import sklearn.discriminant_analysis as sda
import sklearn.linear_model as slm
import sklearn.model_selection as sms
import sklearn.svm as svm
from numpy import set_printoptions
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [18]:
filename = 'data/pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = pd.read_csv(filename, names = names)
data.head()
pd.set_option('display.precision',3)
print(data.head(10))
set_printoptions(precision = 3)

   preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1
5     5   116    74     0     0  25.6  0.201   30      0
6     3    78    50    32    88  31.0  0.248   26      1
7    10   115     0     0     0  35.3  0.134   29      0
8     2   197    70    45   543  30.5  0.158   53      1
9     8   125    96     0     0   0.0  0.232   54      1


3.	Сохраните в переменную array значения признаков, обратившись к атрибуту values.

In [19]:
array = data.values

4.	Выделите в переменной array часть, которая относится к факторным признакам, назовите ее X, и часть, которая относится к результативному признаку, - Y. Прокомментируйте содержимое переменных X и Y.

In [20]:
X = array[:, 1:]
Y = array[:, 0]

print("X:", X.shape)
print("Y:", Y.shape)

X: (768, 8)
Y: (768,)


В качестве Y результативного фактора был выбран диагноз (1 столбец), а Х оставшиеся признаки в качестве факторныхх признаков

5.	Создайте объект разбиения на фолды с помощью функции KFold(n_splits= n_splits, random_state = random_state, shuffle=True) из модуля sklearn.model_selection. Результат запишите в переменную kfold. На вход данной функции подайте следующую информацию: 1) количество частей, на которые должна разбиваться выборка (n_splits), - пусть 10; 2) счетчик случайных чисел (random_state) – пусть 7; 3) необходимость перемешивания данных выборки при каждой оценке, задав параметр shuffle=True.  

In [21]:
kfold = sms.KFold(n_splits=10, random_state=7, shuffle=True)

6.	Постройте модель ближайшего соседа, воспользовавшись функцией KNeighborsClassifier() из модуля sklearn.neighbors. Результат запишите в переменную model. По умолчанию k принимается равным 5. Вы можете изменить настройки, задав другое значение параметра n_neighbors. Параметр weights отвечает за веса наблюдений. По умолчанию они одинаковые, взяты из равномерного распределения. Соответственно, вероятность каждого наблюдения равна 1/n, где n – число наблюдений

In [22]:
model = KNeighborsClassifier(n_neighbors=5, weights="uniform")

7.	Проведите кросс-валидацию, воспользовавшись функцией cross_val_score(model, X, Y, cv=kfold) из модуля sklearn.model_selection. Результат запишите в переменную results.

In [23]:
results = sms.cross_val_score(model, X, Y, cv=kfold)

Выведите на экран среднюю долю правильных ответов (accuracy) и стандартное отклонение полученных оценок, воспользовавшись функциями mean() и std() соответственно

In [24]:
print ("Среднее", np.mean(results))
print ("Стандартное отклоение", np.std(results))

Среднее 0.16543062200956937
Стандартное отклоение 0.034737569908633414


9.	Обучите модель на всех данных с помощью функции fit().

In [25]:
model.fit(X, Y)

KNeighborsClassifier()

10.	Произвольно задайте значения факторных признаков для двух новых наблюдений. Поместите их в переменную x_new.

In [26]:
x_new = np.array([[5, 16, 34, 34, 0.126, 0.012, 0.3, 0.123],
                  [12, 2, 150, 363, 0.415, 0.321, 0.33, 0.28]])

По обученной модели дайте прогноз классов для новых наблюдений, воспользовавшись функцией predict()

In [27]:
model.predict(x_new)

array([1., 2.])

12.	По обученной модели дайте прогноз вероятности классов для новых наблюдений, воспользовавшись функцией predict_proba().

In [28]:
model.predict_proba(x_new)

array([[0. , 0.6, 0.2, 0. , 0. , 0. , 0.2, 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. ],
       [0. , 0. , 0.4, 0. , 0. , 0.2, 0.2, 0. , 0. , 0.2, 0. , 0. , 0. ,
        0. , 0. , 0. , 0. ]])

13.	Опираясь на п.22 задания 7, сделайте вывод о нормальности распределения факторных признаков и возможности применения гауссовской функции плотности распределения для оценки вероятностей в формуле наивного байесовского классификатора. Воспользуйтесь документацией метода для подбора подходящей функции, если это нужно. Прокомментируйте результат.

Я поняла что я ничего не поняла что нужно сделать. Но мой подход решаем проблемы по мере их поступления, поэтому дальше использовалась функция написаная в пункте 14.

14.	Постройте модель наивного байесовского классификатора, воспользовавшись функцией GaussianNB() из модуля sklearn.naive_bayes. Результат запишите в переменную model. Можете воспользоваться другой функцией, исходя из ответа в п.13.

In [29]:
model_gauss = GaussianNB()

15.	Проведите кросс-валидацию, воспользовавшись функцией cross_val_score(model, X, Y, cv=kfold) из модуля sklearn.model_selection. Результат запишите в переменную results.  

In [30]:
results_gauss = sms.cross_val_score(model_gauss, X, Y, cv=kfold)

16.	Выведите на экран среднюю долю правильных ответов (accuracy) и стандартное отклонение полученных оценок, воспользовавшись функциями mean() и std() соответственно.

In [31]:
print ("Среднее", np.mean(results_gauss))
print ("Стандартное отклоение", np.std(results_gauss))

Среднее 0.19143882433356119
Стандартное отклоение 0.0292805816002982


17.	Обучите модель на всех данных с помощью функции fit().

In [32]:
model_gauss.fit(X, Y)

GaussianNB()

По обученной модели дайте прогноз классов для новых наблюдений, воспользовавшись функцией predict().

In [33]:
model_gauss.predict(x_new)

array([0., 0.])

По обученной модели дайте прогноз вероятности классов для новых наблюдений, воспользовавшись функцией predict_proba().

In [34]:
model_gauss.predict_proba(x_new)

array([[8.996e-01, 1.269e-02, 5.941e-02, 2.913e-03, 1.938e-07, 2.068e-07,
        2.529e-02, 4.237e-07, 7.260e-06, 2.761e-14, 7.039e-05, 7.426e-21,
        4.233e-28, 3.103e-18, 0.000e+00, 0.000e+00, 0.000e+00],
       [9.995e-01, 1.600e-08, 4.826e-04, 4.252e-10, 1.499e-12, 2.102e-12,
        2.074e-05, 8.311e-08, 2.044e-06, 7.697e-20, 6.308e-10, 1.410e-22,
        1.150e-37, 2.254e-24, 0.000e+00, 0.000e+00, 0.000e+00]])

20.	Постройте модель решающего дерева, воспользовавшись функцией DecisionTreeClassifier() из модуля sklearn.tree. Результат запишите в переменную model.

In [35]:
model_tree = DecisionTreeClassifier()

21.	Проведите кросс-валидацию, воспользовавшись функцией cross_val_score(model, X, Y, cv=kfold) из модуля sklearn.model_selection. Результат запишите в переменную results.  

In [36]:
results_tree = sms.cross_val_score(model_tree, X, Y, cv=kfold)

22.	Выведите на экран среднюю долю правильных ответов (accuracy) и стандартное отклонение полученных оценок, воспользовавшись, соответственно, функциями mean() и std().

In [37]:
print ("Среднее", np.mean(results_tree))
print ("Стандартное отклоение", np.std(results_tree))

Среднее 0.17043745727956255
Стандартное отклоение 0.053385996650686586


23.	Обучите модель решающего дерева на всех данных, воспользовавшись функцией fit().

In [38]:
model_tree.fit(X, Y)

DecisionTreeClassifier()

По обученной модели дайте прогноз классов для новых наблюдений, воспользовавшись функцией predict()

In [39]:
model_tree.predict(x_new)

array([1., 1.])

25.	По обученной модели дайте прогноз вероятности классов для новых наблюдений, воспользовавшись функцией predict_proba(). Вероятность – это доля наблюдений данного класса в листе.

In [40]:
model_tree.predict_proba(x_new)

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.]])

26.	Создайте пустой список и запишите его в переменную models.

In [41]:
models = []

27.	Добавьте в список models с помощью функции append() набор из кортежей, первый элемент которого содержит название модели, а второй – функцию для создания соответствующей модели. Включите все линейные и нелинейные модели, рассмотренные в заданиях 7 и 8. Можно при этом воспользоваться следующими сокращениями:

In [42]:
models.append(('LR', slm.LogisticRegression(solver='liblinear')))
models.append(('SVM', svm.SVC(kernel='linear')))
models.append(('LDA', sda.LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('NB', GaussianNB()))
models.append(('CART', DecisionTreeClassifier()))

28.	Создайте пустые списки results и names.

In [43]:
results = []
names = []

29.	Задайте критерий оценки качества моделей классификации в переменной scoring. Пусть – доля правильных ответов (accuracy).

In [44]:
scoring = 'accuracy'

30.	С помощью функции for, обращаясь к имени и объекту модели, которые содержатся в кортежах списка models, выполните следующее:


1.   Задайте разбиение выборки на фолды с помощью функции KFold(n_splits=10, random_state=7, shuffle=True). Результат запишите в переменную kfold.
2.   Проведите кросс-валидацию, воспользовавшись функцией cross_val_score(model, X, Y, cv=kfold, scoring=scoring). Результат запишите в переменную cv_results.
3. Добавьте полученные результаты (cv_results) в список results, воспользовавшись функцией append().
4. Добавьте в список names имя рассмотренной модели, воспользовавшись функцией append().
5. С помощью функции print() выведите на экран список названий моделей с соответствующими значениями средней доли правильных ответов (функция mean()) и стандартного отклонения (функция std()), рассчитанными на кросс-валидации.

In [45]:
for name, model in models:
    kfold = sms.KFold(n_splits=10, random_state=7, shuffle=True)
    cv_results = sms.cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
    results.append(cv_results)
    names.append(name)
    print(f"Модель: {name}, Accuracy: {cv_results.mean()}, Стандартное отклонение: {cv_results.std()}")

Модель: LR, Accuracy: 0.2108339029391661, Стандартное отклонение: 0.037965048755044056


KeyboardInterrupt: 

In [ ]:
fig = plt.figure()
fig.suptitle('Сравнение моделей')
ax = fig.add_subplot(111)
plt.boxplot(results)
ax.set_xticklabels(names)
plt.show()